---

- name: "[azure role] - Create an availability set with advanced options"
  azure_rm_availabilityset:
    name: "{{ azure_server_availabilityset_name }}"
    location: "{{ azure_location }}"
    resource_group: "{{ azure_resource_group }}"
    platform_update_domain_count: "{{ azure_server_availabilityset_platform_update_domain_count }}"
    platform_fault_domain_count: "{{ azure_server_availabilityset_platform_fault_domain_count }}"
    sku: "{{ azure_server_availabilityset_sku }}"
    tags:
        Environment: "{{ azure_environment }}"
  when: azure_server_availabilityset_enabled == 'true'

- name: "[azure role] - Create VM without AvaliableSet"
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_server_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    state: present
    vm_size: "{{ azure_server_vm_size }}"
    storage_account_name: "{{ azure_server_account_storage_name }}"
    managed_disk_type: "{{ azure_server_managed_disk_type }}"
    data_disks:
    - lun: 0
      disk_size_gb: "{{ azure_server_managed_disk_size_gb }}"
      managed_disk_type: "{{ azure_server_managed_disk_type }}"
      storage_account_name: "{{ azure_server_account_storage_name }}"
    - lun: 1
      disk_size_gb: "{{ azure_server_managed_disk_size_gb_swap }}"
      managed_disk_type: "{{ azure_server_managed_disk_type }}"
      storage_account_name: "{{ azure_server_account_storage_name }}"
    admin_username: "{{ azure_server_username }}"
    admin_password: "{{ azure_server_password }}"
    network_interfaces: "{{ azure_server_network_interface_name }}"
    image:
      offer: "{{ azure_server_image_offer }}"
      publisher: "{{ azure_server_image_publisher }}"
      sku: "{{ azure_server_image_sku }}"
      version: "{{ azure_server_image_version }}"
    tags:
        Environment: "{{ azure_environment }}"
  when: azure_server_availabilityset_enabled  == 'false'

- name: "[azure role] - Create VM with AvaliableSet"
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_server_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    state: present
    vm_size: "{{ azure_server_vm_size }}"
    storage_account_name: "{{ azure_server_account_storage_name }}"
    managed_disk_type: "{{ azure_server_managed_disk_type }}"
    data_disks:
    - lun: 0
      disk_size_gb: "{{ azure_server_managed_disk_size_gb }}"
      managed_disk_type: "{{ azure_server_managed_disk_type }}"
      storage_account_name: "{{ azure_server_account_storage_name }}"
    - lun: 1
      disk_size_gb: "{{ azure_server_managed_disk_size_gb_swap }}"
      managed_disk_type: "{{ azure_server_managed_disk_type }}"
      storage_account_name: "{{ azure_server_account_storage_name }}"
    admin_username: "{{ azure_server_username }}"
    admin_password: "{{ azure_server_password }}"
    network_interfaces: "{{ azure_server_network_interface_name }}"
    availability_set: "{{ azure_server_availabilityset_name }}"
    image:
      offer: "{{ azure_server_image_offer }}"
      publisher: "{{ azure_server_image_publisher }}"
      sku: "{{ azure_server_image_sku }}"
      version: "{{ azure_server_image_version }}"
    tags:
        Environment: "{{ azure_environment }}"
  when: azure_server_availabilityset_enabled  == 'true'

