---

- name: "[azure role] - Create Network Security Group that allows SSH and service access"
  azure_rm_securitygroup:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_server_network_security_group }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    state: present
    tags:
        Environment: "{{ azure_environment }}"
    rules:
      - name: "{{ item.name }}"
        protocol: "{{ item.protocol }}"
        destination_port_range: "{{ item.port }}"
        access: Allow
        priority: "{{ item.priority }}"
        direction: Inbound
  with_items:
       "{{ azure_server_services }}" 

- name: "[azure role] - Create public IP address"
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    allocation_method: "{{ azure_server_nic_ip_config_public_ip_allocation_method }}"
    name: "{{ azure_server_name }}-ip"
    domain_name: "{{ azure_server_service_name }}-{{ azure_environment_lower }}"
  when: azure_server_nic_ip_config_public_ip == "yes"

- name: "[azure role] - Create virtual network inteface card IP (public)"
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_server_network_interface_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    state: present
    virtual_network_name: "{{ azure_server_vnet_name }}"
    subnet_name: "{{ azure_server_subnet_name }}"
    security_group: "{{ azure_server_network_security_group }}"
    os_type: "{{ azure_server_network_interface_os_type }}"
    public_ip: "yes"
    ip_configurations:
      - name: "{{ azure_server_nic_ip_config_name }}"
        private_ip_allocation_method: "{{ azure_server_nic_ip_config_private_ip_allocation_method }}"
        private_ip_address: "{{ azure_server_nic_ip_config_private_ip_address }}"
        public_ip_address_name: "{{ azure_server_name }}-ip"
        
    tags:
        Environment: "{{ azure_environment }}"
  when: azure_server_nic_ip_config_public_ip == "yes"

- name: "[azure role] - Create virtual network inteface card IP (private only)"
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_server_network_interface_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    state: present
    virtual_network_name: "{{ azure_server_vnet_name }}"
    subnet_name: "{{ azure_server_subnet_name }}"
    security_group: "{{ azure_server_network_security_group }}"
    os_type: "{{ azure_server_network_interface_os_type }}"
    public_ip: no
    ip_configurations:
      - name: "{{ azure_server_nic_ip_config_name }}"
        private_ip_allocation_method: "{{ azure_server_nic_ip_config_private_ip_allocation_method }}"
        private_ip_address: "{{ azure_server_nic_ip_config_private_ip_address }}"

    tags:
        Environment: "{{ azure_environment }}"
  when: azure_server_nic_ip_config_public_ip == "no" or azure_server_nic_ip_config_public_ip is not defined or azure_server_nic_ip_config_public_ip == ""

