---

    - name: "[azure role] - Delete VM"
      azure_rm_virtualmachine:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_server_name }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_client_secret }}"
        subscription_id: "{{ azure_subscription_id }}"
        tenant: "{{ azure_tenant }}"
        state: absent
        vm_size: "{{ azure_server_vm_size }}"
        admin_username: "{{ azure_server_username }}"
        admin_password: "{{ azure_server_password }}"
        network_interfaces: "{{ azure_server_network_interface_name }}"
        image:
          offer: "{{ azure_server_image_offer }}"
          publisher: "{{ azure_server_image_publisher }}"
          sku: "{{ azure_server_image_sku }}"
          version: "{{ azure_server_image_version }}"

    - name: "[azure role] - Delete virtual network inteface card"
      azure_rm_networkinterface:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_server_network_interface_name }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_client_secret }}"
        subscription_id: "{{ azure_subscription_id }}"
        tenant: "{{ azure_tenant }}"
        state: absent
        virtual_network_name: "{{ azure_server_vnet_name }}"
        subnet_name: "{{ azure_server_subnet_name }}"
        security_group: "{{ azure_server_network_security_group }}"
        os_type: "{{ azure_server_network_interface_os_type }}"
        ip_configurations:
          - name: "{{ azure_server_nic_ip_config_name }}"
            private_ip_allocation_method: "{{ azure_server_nic_ip_config_private_ip_allocation_method }}"
            private_ip_address: "{{ azure_server_nic_ip_config_private_ip_address }}"

    - name: "[azure role] - Delete Network Security Group that allows SSH and service access"
      azure_rm_securitygroup:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_server_network_security_group }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_client_secret }}"
        subscription_id: "{{ azure_subscription_id }}"
        tenant: "{{ azure_tenant }}"
        state: absent

    - name: "[azure role] - Delete Public IP"
      azure_rm_publicipaddress:
        name: "{{ azure_server_name }}-ip"
        resource_group: "{{ azure_resource_group }}"
        state: absent
      when: azure_server_nic_ip_config_public_ip == "yes"

    - name: "[azure role] - Delete storage account"
      azure_rm_storageaccount:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_server_account_storage_name }}"
        account_type: "{{ azure_server_account_storage_type }}"
        state: absent
        tags:
            Environment: "{{ azure_environment }}"
      when: azure_server_account_storage_blob is defined or azure_server_account_storage_blob != ""
