#!/bin/sh
echo "Registrando variaveis de ambiente padroes (DEV)"

export ENVIRONMENT=DEV
export AZURE_CLIENT_ID=
export AZURE_SECRET=
export AZURE_SUBSCRIPTION_ID=
export AZURE_TENANT=
#
export VM_SERVER_VM_SIZE=Standard_B1ms
export VM_PRIVATE_IP=
export VM_SERVER_USERNAME=
export VM_SERVER_USERPASSWORD=
export VM_SERVER_VNET_NAME=
export VM_SERVER_SUBNET_NAME=
export VM_K8S_CONTEXT=
#
echo ENVIRONMENT = $ENVIRONMENT
echo AZURE_CLIENT_ID = $AZURE_CLIENT_ID
echo AZURE_SECRET = $AZURE_SECRET
echo AZURE_SUBSCRIPTION_ID = $AZURE_SUBSCRIPTION_ID
echo AZURE_TENANT = $AZURE_TENANT
echo MYSQL_SERVER_NAME = $MYSQL_SERVER_NAME
echo MYSQL_ROOT_USERNAME = $MYSQL_ROOT_USERNAME
echo MYSQL_ROOT_USERPASSWORD = $MYSQL_ROOT_USERPASSWORD
echo VM_PRIVATE_IP = $VM_PRIVATE_IP
echo "Concluido"
