#!/bin/sh
echo "Registrando variaveis de ambiente padroes"
##DEV
#export ENVIRONMENT=DEV
# export AZURE_CLIENT_ID=cd837fef-9ee6-4f16-8c6a-cbe8ca5a3e04
# export AZURE_SECRET=KwmPBS0eMZ009md7CblJvydyP8OCIhxl4S8zeA876Qk=
# export AZURE_SUBSCRIPTION_ID=2c8f6873-a2f7-4b23-898d-25c24cd24f88
# export AZURE_TENANT=2ed3917a-33f9-4b36-80ed-3697e30505b0
#
##AGENT
export ENVIRONMENT=HML
export AZURE_CLIENT_ID=
export AZURE_SECRET=
export AZURE_SUBSCRIPTION_ID=
export AZURE_TENANT=
#
export VM_PREFIX=
export VM_SERVER_VM_SIZE=
export VM_PRIVATE_IP=
export VM_SERVER_USERNAME=
export VM_SERVER_USERPASSWORD=
export VM_SERVER_VNET_NAME=
export VM_SERVER_SUBNET_NAME=
#
echo ENVIRONMENT = $ENVIRONMENT
echo AZURE_CLIENT_ID = $AZURE_CLIENT_ID
echo AZURE_SECRET = $AZURE_SECRET
echo AZURE_SUBSCRIPTION_ID = $AZURE_SUBSCRIPTION_ID
echo AZURE_TENANT = $AZURE_TENANT
echo VM_PRIVATE_IP = $VM_PRIVATE_IP
echo "Concluido"
