echo "Registrando variaveis de ambiente padroes (DEV)"
SET ENVIRONMENT=QA
SET AZURE_CLIENT_ID=39d87c21-81b7-41ab-be98-ee876e14c324
SET AZURE_SECRET=DPH5Fe/xSZ4RNUY53fUQdo5SeKAPinKbI8PBkoFeFgQ=
SET AZURE_SUBSCRIPTION_ID=2c8f6873-a2f7-4b23-898d-25c24cd24f88
SET AZURE_TENANT=2ed3917a-33f9-4b36-80ed-3697e30505b0
SET MYSQL_HOST=mysql-qa-oms.mysql.database.azure.com
SET MYSQL_SERVER_NAME=mysql-qa-oms
SET MYSQL_ROOT_USERNAME=omsadmin@mysql-qa-oms
SET MYSQL_ROOT_USERPASSWORD=ProjetoOmni@2018
SET VMAM_BASE_DB_USERNAME=vmcarbon
SET VMAM_BASE_DB_USERPASSWORD=vmcarbon
SET VM_SERVER_VM_SIZE=Standard_B1ms
SET VM_PRIVATE_IP=10.100.5.150
SET VM_SERVER_USERNAME=omsadmin
SET VM_SERVER_USERPASSWORD=omsadmin2K18!
SET VM_SERVER_VNET_NAME=/subscriptions/2c8f6873-a2f7-4b23-898d-25c24cd24f88/resourceGroups/rg-configs-ambientes/providers/Microsoft.Network/virtualNetworks/oms-ambientes-vnet
SET VM_SERVER_SUBNET_NAME=oms-qa-subnet
SET VM_K8S_CONTEXT=k8s-dev-oms

echo ENVIRONMENT = %ENVIRONMENT%
echo AZURE_CLIENT_ID = %AZURE_CLIENT_ID%
echo AZURE_SECRET = %AZURE_SECRET%
echo AZURE_SUBSCRIPTION_ID = %AZURE_SUBSCRIPTION_ID%
echo AZURE_TENANT = %AZURE_TENANT%
echo MYSQL_HOST = %MYSQL_HOST%
echo MYSQL_SERVER_NAME = %MYSQL_SERVER_NAME%
echo MYSQL_ROOT_USERNAME = %MYSQL_ROOT_USERNAME%
echo MYSQL_ROOT_USERPASSWORD = %MYSQL_ROOT_USERPASSWORD%
echo VMAM_BASE_DB_USERNAME = %VMAM_BASE_DB_USERNAME%
echo VMAM_BASE_DB_USERPASSWORD = %VMAM_BASE_DB_USERPASSWORD%
echo VM_SERVER_VM_SIZE = %VM_SERVER_VM_SIZE%
echo VM_PRIVATE_IP = %VM_PRIVATE_IP%
echo VM_SERVER_USERNAME = %VM_SERVER_USERNAME%
echo VM_SERVER_USERPASSWORD = %VM_SERVER_USERPASSWORD%
echo VM_SERVER_VNET_NAME = %VM_SERVER_VNET_NAME%
echo VM_SERVER_SUBNET_NAME = %VM_SERVER_SUBNET_NAME%
echo VM_K8S_CONTEXT = %VM_K8S_CONTEXT%

echo "Concluido"
PAUSE
