---
- debug:
    msg: "azure_environment {{ azure_environment }}"

- name: Create storage account
  azure_rm_storageaccount:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_server_account_storage_name }}"
    account_type: "{{ azure_vm_server_account_storage_type }}"
    tags:
        Environment: "{{ azure_environment }}"

- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_server_network_security_group }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    state: present
    tags:
        Environment: "{{ azure_environment }}"
    rules:
      - name: SSH_22
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 300
        direction: Inbound

- name: Create virtual network inteface card
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_server_network_interface_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    state: present
    virtual_network_name: "{{ azure_vm_server_vnet_name }}"
    subnet_name: "{{ azure_vm_server_subnet_name }}"
    security_group: "{{ azure_vm_server_network_security_group }}"
    os_type: "{{ azure_vm_server_network_interface_os_type }}"
    public_ip: no
    ip_configurations:
      - name: "{{ azure_vm_server_nic_ip_config_name }}"
        private_ip_allocation_method: "{{ azure_vm_server_nic_ip_config_private_ip_allocation_method }}"
        private_ip_address: "{{ azure_vm_server_nic_ip_config_private_ip_addrees }}"
    tags:
        Environment: "{{ azure_environment }}"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_server_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    state: present
    vm_size: "{{ azure_vm_server_vm_size }}"
    storage_account_name: "{{ azure_vm_server_account_storage_name }}"
    managed_disk_type: "{{ azure_vm_server_managed_disk_type }}"
    admin_username: "{{ azure_vm_server_username }}"
    admin_password: "{{ azure_vm_server_password }}"
    network_interfaces: "{{ azure_vm_server_network_interface_name }}"
    image:
      offer: "{{ azure_vm_server_image_offer }}"
      publisher: "{{ azure_vm_server_image_publisher }}"
      sku: "{{ azure_vm_server_image_sku }}"
      version: "{{ azure_vm_server_image_version }}"
    tags:
        Environment: "{{ azure_environment }}"

- name: Reload known_hosts
  command: ssh-keygen -R {{ azure_vm_server_nic_ip_config_private_ip_addrees }}
